import { Injectable } from '@angular/core';
import { MaskitoOptions } from '@maskito/core';

export type Country = {
    name: string;
    value: string;
};

export const countryListIcons: Array<Country> = [
    { name: '🇷🇴', value: 'RO' },
    { name: '🇫🇷', value: 'FR' },
    { name: '🇬🇧', value: 'GB' },
    { name: '🇪🇸', value: 'ES' },
    { name: '🇳🇱', value: 'NL' },
    { name: '🇮🇹', value: 'IT' },
    { name: '🇺🇸', value: 'US' },
    { name: '🇨🇦', value: 'CA' },
    { name: '🇦🇺', value: 'AU' },
    { name: '🇩🇪', value: 'DE' },
    { name: '🇧🇪', value: 'BE' },
    { name: '🇨🇭', value: 'CH' },
    { name: '🇦🇹', value: 'AT' },
    { name: '🇵🇹', value: 'PT' },
    { name: '🇬🇷', value: 'GR' },
    { name: '🇸🇪', value: 'SE' },
    { name: '🇳🇴', value: 'NO' },
    { name: '🇩🇰', value: 'DK' },
    { name: '🇫🇮', value: 'FI' },
    { name: '🇮🇪', value: 'IE' },
    { name: '🇱🇺', value: 'LU' },
    { name: '🇲🇨', value: 'MC' },
    { name: '🇸🇲', value: 'SM' },
    { name: '🇸🇮', value: 'SI' },
    { name: '🇭🇷', value: 'HR' },
    { name: '🇧🇦', value: 'BA' },
    { name: '🇲🇪', value: 'ME' },
    { name: '🇽🇰', value: 'XK' },
];

@Injectable({ providedIn: 'root' })
export class PhoneNumberMaskService {
    private readonly phoneMaskList: Array<{
        countryCode: string;
        mask: MaskitoOptions;
    }> = [
        {
            countryCode: countryListIcons.find((c) => c.value === 'RO').value,
            mask: {
                mask: [
                    '+',
                    '4',
                    '0',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    '-',
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'GB').value,
            mask: {
                mask: [
                    '+',
                    '4',
                    '4',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'US').value,
            mask: {
                mask: [
                    '+',
                    '1',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    '-',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'CA').value,
            mask: {
                mask: [
                    '+',
                    '1',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    '-',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'AU').value,
            mask: {
                mask: [
                    '+',
                    '6',
                    '1',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    '-',
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'FR').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '3',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'DE').value,
            mask: {
                mask: [
                    '+',
                    '4',
                    '9',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        // please complete the list with the rest of the countries from countryListIcons
        {
            countryCode: countryListIcons.find((c) => c.value === 'IT').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '9',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'ES').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '4',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'NL').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '1',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'BE').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '2',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'CH').value,
            mask: {
                mask: [
                    '+',
                    '4',
                    '1',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'AT').value,
            mask: {
                mask: [
                    '+',
                    '4',
                    '3',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'PT').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '5',
                    '1',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'GR').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '0',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'SE').value,
            mask: {
                mask: [
                    '+',
                    '4',
                    '6',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'NO').value,
            mask: {
                mask: [
                    '+',
                    '4',
                    '7',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'DK').value,
            mask: {
                mask: [
                    '+',
                    '4',
                    '5',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'FI').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '5',
                    '8',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'IE').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '5',
                    '3',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'LU').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '5',
                    '2',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'MC').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '7',
                    '7',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'SM').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '7',
                    '8',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'SI').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '8',
                    '6',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'HR').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '8',
                    '5',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'BA').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '8',
                    '7',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'ME').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '8',
                    '2',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
        {
            countryCode: countryListIcons.find((c) => c.value === 'XK').value,
            mask: {
                mask: [
                    '+',
                    '3',
                    '8',
                    '1',
                    ' ',
                    '(',
                    /\d/,
                    /\d/,
                    /\d/,
                    ')',
                    ' ',
                    /\d/,
                    /\d/,
                    /\d/,
                    /\d/,
                ],
            },
        },
    ];

    public getMaskByCountryCode(countryCode: string): MaskitoOptions {
        return this.phoneMaskList.find((m) => m.countryCode === countryCode)
            ?.mask;
    }

    public matchAndGetMaskByPhoneNumber(phoneNumber: string): Country | null {
        if (!phoneNumber) {
            return countryListIcons.find((c) => c.value === 'RO');
        }

        const countryPhonePrefix = phoneNumber.substring(0, 3);

        const countryCode = this.phoneMaskList.find((m) => {
            const mask = m.mask.mask as string[];
            const maskPrefix = mask.slice(0, 3).join('');
            return maskPrefix === countryPhonePrefix;
        });

        return countryListIcons.find(
            (c) => c.value === countryCode?.countryCode
        );
    }
}
