import { Injectable } from '@angular/core';
import { SearcheableSelectModel } from '@shared';
import { Observable, of } from 'rxjs';

interface ColorOptions extends SearcheableSelectModel {
    name: string;
}

enum ColorGroup {
    Aidite3DPro = 'Aidite 3D Pro',
    Vita3dMaster = 'Vita 3D Master',
    Ivoclar = 'Ivoclar',
}
@Injectable()
export class ColorFacade {
    public getAll$(): Observable<ColorOptions[]> {
        const colors: ColorOptions[] = [
            {
                id: '1',
                value: 'A1',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'A1 color',
                name: 'A1' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '2',
                value: 'A2',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'A2 color',
                name: 'A2' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '3',
                value: 'A3',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'A3 color',
                name: 'A3' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '4',
                value: 'A3.5',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'A3.5 color',
                name: 'A3.5' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '5',
                value: 'A4',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'A4 color',
                name: 'A4' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '6',
                value: 'B1',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'B1 color',
                name: 'B1' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '7',
                value: 'B2',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'B2 color',
                name: 'B2' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '8',
                value: 'B3',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'B3 color',
                name: 'B3' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '9',
                value: 'B4',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'B4 color',
                name: 'B4' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '10',
                value: 'C1',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'C1 color',
                name: 'C1' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '11',
                value: 'C2',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'C2 color',
                name: 'C2' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '12',
                value: 'C3',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'C3 color',
                name: 'C3' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '13',
                value: 'C4',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'C4 color',
                name: 'C4' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '14',
                value: 'D2',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'D2 color',
                name: 'D2' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '15',
                value: 'D3',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'D3 color',
                name: 'D3' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '16',
                value: 'D4',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'D4 color',
                name: 'D4' + ' - ' + ColorGroup.Aidite3DPro,
            },
            {
                id: '17',
                value: 'H',
                group: ColorGroup.Aidite3DPro,
                isSelected: false,
                displayBoth: true,
                description: 'H color',
                name: 'H' + ' - ' + ColorGroup.Aidite3DPro,
            },
            // Vita 3D Master
            {
                id: '18',
                value: '0M1',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '0M1 color',
                name: '0M1' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '19',
                value: '0M2',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '0M2 color',
                name: '0M2' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '20',
                value: '0M3',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '0M3 color',
                name: '0M3' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '21',
                value: '1M1',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '1M1 color',
                name: '1M1' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '22',
                value: '1M2',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '1M2 color',
                name: '1M2' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '23',
                value: '2L1.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '2L1.5 color',
                name: '2L1.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '24',
                value: '2L2.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '2L2.5 color',
                name: '2L2.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '25',
                value: '2M1',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '2M1 color',
                name: '2M1' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '26',
                value: '2M2',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '2M2 color',
                name: '2M2' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '27',
                value: '2M3',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '2M3 color',
                name: '2M3' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '28',
                value: '2R1.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '2R1.5 color',
                name: '2R1.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '29',
                value: '2R2.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '2R2.5 color',
                name: '2R2.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '30',
                value: '3L1.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '3L1.5 color',
                name: '3L1.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '31',
                value: '3L2.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '3L2.5 color',
                name: '3L2.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '32',
                value: '3M1',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '3M1 color',
                name: '3M1' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '33',
                value: '3M2',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '3M2 color',
                name: '3M2' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '34',
                value: '3M3',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '3M3 color',
                name: '3M3' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '35',
                value: '3R1.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '3R1.5 color',
                name: '3R1.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '36',
                value: '3R2.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '3R2.5 color',
                name: '3R2.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '37',
                value: '4L1.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '4L1.5 color',
                name: '4L1.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '38',
                value: '4L2.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '4L2.5 color',
                name: '4L2.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '39',
                value: '4M1',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '4M1 color',
                name: '4M1' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '40',
                value: '4M2',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '4M2 color',
                name: '4M2' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '41',
                value: '4M3',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '4M3 color',
                name: '4M3' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '42',
                value: '4R1.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '4R1.5 color',
                name: '4R1.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '43',
                value: '4R2.5',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '4R2.5 color',
                name: '4R2.5' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '44',
                value: '5M1',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '5M1 color',
                name: '5M1' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '45',
                value: '5M2',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '5M2 color',
                name: '5M2' + ' - ' + ColorGroup.Vita3dMaster,
            },
            {
                id: '46',
                value: '5M3',
                group: ColorGroup.Vita3dMaster,
                isSelected: false,
                displayBoth: true,
                description: '5M3 color',
                name: '5M3' + ' - ' + ColorGroup.Vita3dMaster,
            },
            // Ivoclar
            {
                id: '47',
                value: 'BL1',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'BL1 color',
                name: 'BL1' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '48',
                value: 'BL2',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'BL2 color',
                name: 'BL2' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '49',
                value: 'BL3',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'BL3 color',
                name: 'BL3' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '50',
                value: 'BL4',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'BL4 color',
                name: 'BL4' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '51',
                value: 'A1',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'A1 color',
                name: 'A1' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '52',
                value: 'A2',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'A2 color',
                name: 'A2' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '53',
                value: 'A3',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'A3 color',
                name: 'A3' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '54',
                value: 'A3.5',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'A3.5 color',
                name: 'A3.5' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '55',
                value: 'A4',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'A4 color',
                name: 'A4' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '56',
                value: 'B1',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'B1 color',
                name: 'B1' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '57',
                value: 'B2',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'B2 color',
                name: 'B2' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '58',
                value: 'B3',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'B3 color',
                name: 'B3' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '59',
                value: 'B4',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'B4 color',
                name: 'B4' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '60',
                value: 'C1',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'C1 color',
                name: 'C1' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '61',
                value: 'C2',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'C2 color',
                name: 'C2' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '62',
                value: 'C3',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'C3 color',
                name: 'C3' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '63',
                value: 'C4',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'C4 color',
                name: 'C4' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '64',
                value: 'D2',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'D2 color',
                name: 'D2' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '65',
                value: 'D3',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'D3 color',
                name: 'D3' + ' - ' + ColorGroup.Ivoclar,
            },
            {
                id: '66',
                value: 'D4',
                group: ColorGroup.Ivoclar,
                isSelected: false,
                displayBoth: true,
                description: 'D4 color',
                name: 'D4' + ' - ' + ColorGroup.Ivoclar,
            },
        ];

        return of(colors);
    }
}
